config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/about'

  root 'welcome#index'

  
  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end
    
    def edit
        @article = Article.find(params[:id])
    end
    
    def create
        @article = Article.new(article_params)
 
        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end
    
    def update
        @article = Article.find(params[:id])

        if @article.update(article_params)
            redirect_to @article
        else
            render 'edit'
        end
    end
    
    def destroy
        @article = Article.find(params[:id])
        @article.destroy

        redirect_to articles_path
    end
    
    private
        def article_params
            params.require(:article).permit(:title, :text)
        end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        
        redirect_to article_path(@article)
    end
    
    def destroy
        @article = Article.find(params[:article_id])
        
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        
        redirect_to article_path(@article)
    end

    private
        def comment_params
            params.require(:comment).permit(:commenter, :body)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @latest_articles = Article.last(5).reverse
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<article>
    <%= link_to image_tag("pic01.jpg"), article_path(article), class: "image" %>
    <div class="inner">
	    <h4><%= link_to article.title, article_path(article) %></h4>
	    <p>
	        <%= strip_tags(article.text[0..124]) %>
	        <%= ' [...] ' if article.text.length > 125 %>
	        <%= link_to 'Read more', article_path(article) if article.text.length > 125 %>
        </p>
    </div>
</article>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.cktext_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<section id="one">
	<div class="container">
		<header class="major">
			<h2>Editing Article</h2>
			<p></p>
		</header>
		
		<%= render 'form' %>
		
		<%= link_to 'Back', articles_path %>
	</div>
</section>

app/views/articles/index.html.erb
<section id="one">
	<div class="container">
		<header class="major">
			<h2>Listing articles</h2>
			<p><br />
			</p>
		</header>
		
		<%= link_to 'New article', new_article_path %>
		
	    <table>
          <tr>
            <th>Title</th>
            <th>Text</th>
            <th colspan="3"></th>
          </tr>
         
          <% @articles.each do |article| %>
            <tr>
              <td><%= article.title %></td>
              <td><%= article.text[0..124] %><%= ' [...] ' if article.text.length > 125 %></td>
              <td><%= link_to 'Show', article_path(article) %></td>
              <td><%= link_to 'Edit', edit_article_path(article) %></td>
              <td><%= link_to 'Delete', article_path(article),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </table>
	</div>
</section>

app/views/articles/new.html.erb
<section id="one">
	<div class="container">
		<header class="major">
			<h2>New Article</h2>
			<p></p>
		</header>
		
		<%= render 'form' %>
		
		<%= link_to 'Back', articles_path %>
	</div>
</section>

app/views/articles/show.html.erb
<section id="one">
	<div class="container">
		<header class="major">
			<h2><%= @article.title %></h2>
			<p></p>
		</header>
		
		<p><%= @article.text.html_safe %></p>
	</div>
</section>

<section id="two">
	<div class="container">
	    <h3>Comments</h3>
	    <div class="comments">
            <%= render @article.comments %>
        </div>
        
        <hr/>
        
	    <h3>Add a comment:</h3>
        <%= render 'comments/form' %>
	</div>
</section>

app/views/comments/_comment.html.erb
<article>
    <div class="image"><%= image_tag "user.png" %></div>
    <div class="inner">
	    <h4><%= comment.commenter %></h4>
	    <p>
	        <%= comment.body %><br/>
	        <%= link_to 'Delete', [comment.article, comment],
                       method: :delete,
                       data: { confirm: 'Are you sure?' } %>
        </p>
    </div>
</article>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= Blog::Application::NAME %></title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <!-- Header -->
    <section id="header">
	    <header>
		    <span class="image avatar"><%= image_tag "avatar.jpg" %></span>
		    <h1 id="logo"><a href="#">Ruben O. Chiavone</a></h1>
		    <p>Lorem Ipsum is simply dummy text of<br />
		    the printing and typesetting industry</p>
	    </header>
	    <nav id="nav">
		    <ul>
		        <li><%= link_to 'Home', controller: 'welcome', action: 'index' %></li>
			    <li><%= link_to 'About', controller: 'welcome', action: 'about' %></li>
			    <li><%= link_to 'Latest Articles', controller: 'welcome', action: 'index', anchor: "latest_articles" %></li>
			    <!--<li><a href="#three">Contact</a></li>-->
		    </ul>
	    </nav>
	    <footer>
		    <ul class="icons">
			    <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
			    <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
			    <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
			    <li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
			    <li><a href="#" class="icon fa-envelope"><span class="label">Email</span></a></li>
		    </ul>
	    </footer>
    </section>

    <!-- Wrapper -->
    <div id="wrapper">

	    <!-- Main -->
	    <div id="main">

	    <%= yield %>

	    <!-- Footer -->
	    <section id="footer">
		    <div class="container">
			    <ul class="copyright">
				    <li>&copy; <%= Time.new.year.to_s + " " + Blog::Application::NAME + " v" + Blog::Application::VERSION %>. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
			    </ul>
		    </div>
	    </section>

    </div>

</body>
</html>

app/views/welcome/about.html.erb
<!-- One -->
<section id="one">
	<div class="container">
		<header class="major">
			<h2><%= Blog::Application::NAME %></h2>
			<p>About Me</p>
		</header>
		<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
	</div>
</section>

app/views/welcome/index.html.erb
<!-- One -->
<section id="one">
	<div class="container">
		<header class="major">
			<h2><%= Blog::Application::NAME %></h2>
			<p>Just a nice place to post my stuff<br />
			and have some fun.</p>
		</header>
		<!-- <p>...</p> -->
	</div>
</section>

<!-- Two -->
<section>
	<div id="latest_articles" class="container">
		<h3>Latest posts</h3>
		<!-- <p>...</p> -->
		<div class="features">
		    <%= render @latest_articles %>
		</div>
	</div>
</section>

<!-- Three
<section id="three">
	<div class="container">
		<h3>Contact Me</h3>
		<p>Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum integer. Integer eu ante ornare amet commetus.</p>
		<form method="post" action="#">
			<div class="row uniform">
				<div class="6u 12u(xsmall)"><input type="text" name="name" id="name" placeholder="Name" /></div>
				<div class="6u 12u(xsmall)"><input type="email" name="email" id="email" placeholder="Email" /></div>
			</div>
			<div class="row uniform">
				<div class="12u"><input type="text" name="subject" id="subject" placeholder="Subject" /></div>
			</div>
			<div class="row uniform">
				<div class="12u"><textarea name="message" id="message" placeholder="Message" rows="6"></textarea></div>
			</div>
			<div class="row uniform">
				<div class="12u">
					<ul class="actions">
						<li><input type="submit" class="special" value="Send Message" /></li>
						<li><input type="reset" value="Reset Form" /></li>
					</ul>
				</div>
			</div>
		</form>
	</div>
</section>
 -->